export enum localstorageKey {
  'couponCode' = 'used_coupon_code',
  'pranicSessionId' = 'pranicPurificationSessionId',
  'praanicPayId' = 'dbPay',
  '200TTCRzpId' = '200TTC_razorpay_payment_id',
  '200TTCRzpOrderId' = '200TTC_razorpay_order_id',
  '200TTCRzpSig' = '200TTC_razorpay_signature',
  '200TTCRzpDBId' = '200TTC_razorpay_db_id',
  '200TTCStripeSessionId' = '200TTC_stripe_session_id',
  '200TTCStripeDBId' = '200TTC_stripe_db_id',
  'pranaArambhVideo' = 'prana_arambh',
  '200TTCInstallment' = '200TTC_installment',
  '200TTCDue' = '200TTC_due',
  'rishikesh200RzpId' = 'rishikesh_200_hour_rzp_id',
  'rishikesh200OrderId' = 'rishikesh_200_hour_rzp_order_id',
  'rishikesh200Sig' = 'rishikesh_200_hour_rzp_signature',
  'rishikesh200DBId' = 'rishikesh_200_hour_rzp_db_id',
  'rishikesh20StripeSessionId' = 'rishikesh_200_stripe_session_id',
  'rishikesh200StripeDBId' = 'rishikesh-200_stripe_db_id',

  'swaraSadhnaRzpId' = 'swara_sadhna_rzp_id',
  'swaraSadhnaOrderId' = 'swara_sadhna_rzp_order_id',
  'swaraSadhnaSig' = 'swara_sadhna_rzp_signature',
  'swaraSadhnaDBId' = 'swara_sadhna_rzp_db_id',
  'swaraSadhnaAmnt' = 'swara_sadhna_rzp_amnt',
  'swaraSadhnaUserID' = 'swara_sadhna_user_id',
  'swaraSadhnaStripeSessionId' = 'swara_sadhna_stripe_session_id',
  'swaraSadhnaStripeDBId' = 'swara_sadhna_stripe_db_id',
  'bali300StripeSessionId' = 'bali_300_stripe_session_id',
  'bali300StripeDBId' = 'bali_300_stripe_db_id',
}
