export enum localstorageKey {
  'couponCode' = 'used_coupon_code',
  'pranicSessionId' = 'pranicPurificationSessionId',
  'praanicPayId' = 'dbPay',
  '200TTCRzpId' = '200TTC_razorpay_payment_id',
  '200TTCRzpOrderId' = '200TTC_razorpay_order_id',
  '200TTCRzpSig' = '200TTC_razorpay_signature',
  '200TTCRzpDBId' = '200TTC_razorpay_db_id',
  '200TTCStripeSessionId' = '200TTC_stripe_session_id',
  '200TTCStripeDBId' = '200TTC_stripe_db_id',
  'pranaArambhVideo' = 'prana_arambh',
  '200TTCInstallment' = '200TTC_installment',
  '200TTCDue' = '200TTC_due',
  'rishikesh200RzpId' = "rishikesh_200_hour_rzp_id",
  'rishikesh200OrderId' = "rishikesh_200_hour_rzp_order_id",
  'rishikesh200Sig' = "rishikesh_200_hour_rzp_signature",
  'rishikesh200DBId' = "rishikesh_200_hour_rzp_db_id",
  'rishikesh20StripeSessionId' = 'rishikesh_200_stripe_session_id',
  'rishikesh200StripeDBId' = 'rishikesh-200_stripe_db_id',
}
