export enum localstorageKey {
  'couponCode' = 'used_coupon_code',
  'pranicSessionId' = 'pranicPurificationSessionId',
  'pranicIISessionId' = 'pranicPurificationIISessionId',
  'praanicPayId' = 'dbPay',
  'praanicIIPayId' = 'dbPayII',
  '200TTCRzpId' = '200TTC_razorpay_payment_id',
  '200TTCRzpOrderId' = '200TTC_razorpay_order_id',
  '200TTCRzpSig' = '200TTC_razorpay_signature',
  '200TTCRzpDBId' = '200TTC_razorpay_db_id',
  '200TTCStripeSessionId' = '200TTC_stripe_session_id',
  '200TTCStripeDBId' = '200TTC_stripe_db_id',
  '200TTCPaypalOrderId' = '200TTC_paypal_order_id',
  '200TTCPaypalDBId' = '200TTC_paypal_db_id',
  'pranaArambhVideo' = 'prana_arambh',
  '200TTCInstallment' = '200TTC_installment',
  '200TTCDue' = '200TTC_due',
  'rishikesh200RzpId' = 'rishikesh_200_hour_rzp_id',
  'rishikesh200OrderId' = 'rishikesh_200_hour_rzp_order_id',
  'rishikesh200Sig' = 'rishikesh_200_hour_rzp_signature',
  'rishikesh200DBId' = 'rishikesh_200_hour_rzp_db_id',
  'rishikesh20StripeSessionId' = 'rishikesh_200_stripe_session_id',
  'rishikesh200StripeDBId' = 'rishikesh-200_stripe_db_id',
  'rishikeshPaypalOrderId' = 'rishikesh_paypal_order_id',
  'rishikeshPaypalDBId' = 'rishikesh_paypal_db_id',

  'swaraSadhnaRzpId' = 'swara_sadhna_rzp_id',
  'swaraSadhnaOrderId' = 'swara_sadhna_rzp_order_id',
  'swaraSadhnaSig' = 'swara_sadhna_rzp_signature',
  'swaraSadhnaDBId' = 'swara_sadhna_rzp_db_id',
  'swaraSadhnaAmnt' = 'swara_sadhna_rzp_amnt',
  'swaraSadhnaCurr' = 'swara_sadhna_rzp_curr',
  'swaraSadhnaUserID' = 'swara_sadhna_user_id',
  'swaraSadhnaStripeSessionId' = 'swara_sadhna_stripe_session_id',
  'swaraSadhnaStripeDBId' = 'swara_sadhna_stripe_db_id',
  'swaraSadhnaPaypalOrderId' = 'swara_sadhna_paypal_order_id',
  'swaraSadhnaPaypalDBId' = 'swara_sadhna_paypal_db_id',

  'bali300StripeSessionId' = 'bali_300_stripe_session_id',
  'bali300StripeDBId' = 'bali_300_stripe_db_id',

  'baliPaypalOrderId' = 'bali_paypal_order_id',
  'baliPaypalDBId' = 'bali_paypal_db_id',

  'userSource' = 'user_source',
  'loginId' = 'login_id',
  'pranayamaRzpId' = 'pranayama_rzp_id',
  'pranayamaRzpOrderId' = 'pranayama_rzp_order_id',
  'pranayamaRzpSig' = 'pranayama_rzp_signature',
  'pranayamaRzpDBId' = 'pranayama_rzp_db_id',
  'pranayamaStripeSessionId' = 'pranayama_stripe_session_id',
  'pranayamaStripeDBId' = 'pranayama_stripe_db_id',
  'pranayamaPaypalOrderId' = 'pranayama_paypal_order_id',
  'pranayamaPaypalDBId' = 'pranayama_paypal_db_id',
  'pranayamaInstallment' = 'pranayama_installment',
  'pranayamaDue' = 'pranayama_due',

  'retreatRzpId' = 'retreat_rzp_id',
  'retreatOrderId' = 'retreat_rzp_order_id',
  'retreatSig' = 'retreat_rzp_signature',
  'retreatDBId' = 'retreat_rzp_db_id',
  'retreatAmnt' = 'retreat_rzp_amnt',
  'retreatCurr' = 'retreat_rzp_curr',
  'retreatUserID' = 'retreat_user_id',
  'retreatStripeSessionId' = 'retreat_stripe_session_id',
  'retreatStripeDBId' = 'retreat_stripe_db_id',
  'retreatPaypalOrderId' = 'retreat_paypal_order_id',
  'retreatPaypalDBId' = 'retreat_paypal_db_id',

  'liveClassesPaypalOrderId' = 'live_classes_paypal_order_id',
  'liveClassesPaypalDBId' = 'live_classes_paypal_db_id',

  'pgRzpId' = 'pg_rzp_id',
  'pgOrderId' = 'pg_rzp_order_id',
  'pgSig' = 'pg_rzp_signature',
  'pgDBId' = 'pg_rzp_db_id',
  'pgAmnt' = 'pg_rzp_amnt',
  'pgCurr' = 'pg_rzp_curr',
  'pgUserID' = 'pg_user_id',
  'pgStripeSessionId' = 'pg_stripe_session_id',
  'pgStripeDBId' = 'pg_stripe_db_id',
  'pgPaypalOrderId' = 'pg_paypal_order_id',
  'pgPaypalDBId' = 'pg_paypal_db_id',
  'pranaArambhaPaypalOrderId' = 'prana_arambha_paypal_order_id',
  'pranaArambhaPaypalDBId' = 'prana_arambha_paypal_db_id',
}
