export enum routeEnum {
  '200TTC' = '200-hours-yoga-teacher-training-online',
  'pranicPurification' = 'pranic-purification',
  'pranOnlinePranaArambh' = 'pranayama-course-online-pranarambha',
  '300HourTTCBali' = '300-hour-yoga-teacher-training-in-bali',
  'rishkesh200' = '200-hours-yoga-teacher-training-in-rishikesh',
  'yogaRetreat' = 'yoga-retreat-in-rishikesh-india',
  'rishikesh100' = '100-hours-yoga-teacher-training-in-rishikesh',
  'rishikesh300' = '300-hours-yoga-teacher-training-in-rishikesh',
  'blogs' = 'blogs',
  'rishikesh' = 'get-certified-in-rishikesh',
  'bali' = 'get-certified-in-bali',
  'bali200' = '200-hour-yoga-teacher-training-in-bali',
  'bali300' = '300-hour-yoga-teacher-training-in-bali',
  'bDtox' = 'breath-detox-yoga',
  'online' = 'online-yoga-classes',
  'prashantjPage' = 'yoga-teacher/acharya-prashant-jakhmola/prashantjyoga',
  'aboutPrashantJi' = 'yoga-teacher/acharya-prashant-jakhmola/:id',
  'preRecordPranayamaCourse' = 'pre-recorded-pranayama-courses',
  'swaraSadhana' = 'swara-sadhana',
  'stRegister' = 'student-register',
  'sa' = 'swara-sadhana',
  'freeWebiner' = 'free-webinar'
}
