export enum s3Bucket {
  mainLogo = 'https://my-s3-images-bucket.s3.amazonaws.com/img/logo2.png',
  frontPic = 'https://my-s3-images-bucket.s3.amazonaws.com/images/FERN8524-removebg-preview+(1).png',
  homeAbout = 'https://my-s3-images-bucket.s3.amazonaws.com/images/about_section_fweev7.jpg',
  flower = 'https://my-s3-images-bucket.s3.amazonaws.com/img/flower-color.png',
  flowerWhite = 'https://my-s3-images-bucket.s3.amazonaws.com/img/flower-white.png',
  room1 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc4_ikf9ta.jpg',
  room2 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc3_hbccdh.jpg',
  room3 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc2_zwdgpr.jpg',
  room4 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc1_e2fcux.jpg',
  roomMain = 'https://my-s3-images-bucket.s3.amazonaws.com/images/IMG_6828_cchusm.jpg',
  food = 'https://my-s3-images-bucket.s3.amazonaws.com/images/food_dwn1yl.jpg',
  whiteArrow = 'https://my-s3-images-bucket.s3.amazonaws.com/img/arrow-white.png',
  offer1 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/online4_tuiozj.jpg',
  offer2 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/onluneoff_vriefa.jpg',
  offer3 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/online3_pseqg1.jpg',
  offer4 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/onlinr2_lunr65.jpg',
  calender = 'https://my-s3-images-bucket.s3.amazonaws.com/img/calendar.png',
  person = 'https://my-s3-images-bucket.s3.amazonaws.com/img/user.png',
  hero = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_6446.JPG',
  rishikesh100 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1614.JPG',
  rishikesh200 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1048.JPEG',
  rishikesh300 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/79d6792b-ce4b-458f-808a-af171e291224.jpg',
  bali100 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A9876.JPG',
  bali200 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A0452.JPG',
  bali300 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A0799.JPG',
  certifiedRishikeshAbout = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1587.JPG',
  certifiedWhyBali = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_2828.JPG',
  rishikeshAbout = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A7672.jpg',
  baliAbout = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A9431.JPG',
  rishikesh200Banner = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/_DSC3081.jpg',
  rishi200Certify1 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A0789.JPG',
  rishi200Certify2 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/20221017123612_IMG_8678.jpeg',
  lotusBullet = 'https://my-s3-images-bucket.s3.amazonaws.com/img/bullet.png',
  rishikesh300Banner = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_9926.JPG',
  rishikesh100About1 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/_DSC3854.jpg',
  rishikesh300About1 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_20190324_112943_Bokeh_Original.jpg',

  onlineCourseHero = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_6884_1.JPG',
  onlineCourseAbout1 = 'https://my-s3-images-bucket.s3.amazonaws.com/img/image_1677479957069.JPG',
  courseMentro1 = '../../assets/20190630153357_IMG_0087.JPG',
  courseMentor2 = 'https://my-s3-images-bucket.s3.amazonaws.com/img/image_1695634116777.jpeg',
  courseMentor3 = 'https://my-s3-images-bucket.s3.amazonaws.com/img/IMG_20250331_171325_021.jpg',
  prashantjiHero = 'https://my-s3-images-bucket.s3.amazonaws.com/img/image_1674209054855.jpg',
  prasantAbout1 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/FERN8284.jpg',
  prasantAbout2 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/FERN8341.jpg',
  anujHero1 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/DSC00532_1.jpg',
  anujHero2 = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_3894.JPG',
  taniyaHero = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG-20250704-WA0007.jpg',
  taniyaAbout = 'https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG-20250704-WA0010.jpg',

  prashantIndexAbout = '../../../../assets/new-home/IMG_2820.JPG',
}
export enum youtubeLink {
  trainingImportance = 'https://www.youtube.com/embed/t7l1cqDj1tA?si=ZJCQXJYDLzDwLLvm',
}
