export enum s3Bucket {
  mainLogo = 'https://my-s3-images-bucket.s3.amazonaws.com/img/logo2.png',
  frontPic = 'https://my-s3-images-bucket.s3.amazonaws.com/images/FERN8524-removebg-preview+(1).png',
  homeAbout = 'https://my-s3-images-bucket.s3.amazonaws.com/images/about_section_fweev7.jpg',
  flower = 'https://my-s3-images-bucket.s3.amazonaws.com/img/flower-color.png',
  flowerWhite = 'https://my-s3-images-bucket.s3.amazonaws.com/img/flower-white.png',
  room1 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc4_ikf9ta.jpg',
  room2 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc3_hbccdh.jpg',
  room3 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc2_zwdgpr.jpg',
  room4 = 'https://my-s3-images-bucket.s3.amazonaws.com/images/acc1_e2fcux.jpg',
  roomMain = 'https://my-s3-images-bucket.s3.amazonaws.com/images/IMG_6828_cchusm.jpg',
  food = "https://my-s3-images-bucket.s3.amazonaws.com/images/food_dwn1yl.jpg",
  whiteArrow = "https://my-s3-images-bucket.s3.amazonaws.com/img/arrow-white.png",
  offer1 = "https://my-s3-images-bucket.s3.amazonaws.com/images/online4_tuiozj.jpg",
  offer2 = "https://my-s3-images-bucket.s3.amazonaws.com/images/onluneoff_vriefa.jpg",
  offer3 = "https://my-s3-images-bucket.s3.amazonaws.com/images/online3_pseqg1.jpg",
  offer4 = "https://my-s3-images-bucket.s3.amazonaws.com/images/onlinr2_lunr65.jpg",
  calender = "https://my-s3-images-bucket.s3.amazonaws.com/img/calendar.png",
  person = "https://my-s3-images-bucket.s3.amazonaws.com/img/user.png",
  hero = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_6446.JPG",
  rishikesh100 = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1614.JPG",
  rishikesh200 = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1048.JPEG",
  rishikesh300 = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/79d6792b-ce4b-458f-808a-af171e291224.jpg",
  bali100 = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A9876.JPG",
  bali200 = "../../../assets/954A0452.JPG",
  bali300 = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A0799.JPG",
  certifiedRishikeshAbout = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_1587.JPG",
  certifiedWhyBali = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/IMG_2828.JPG",
  rishikeshAbout = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A7672.jpg",
  baliAbout = "https://my-s3-images-bucket.s3.us-east-1.amazonaws.com/images/954A9431.JPG",
  rishikesh200Banner = "../../../assets/_DSC3081.jpg",
  rishi200Certify1 = "../../../../assets/954A0789.JPG",
  rishi200Certify2 = "../../../../assets/20221017123612_IMG_8678.jpeg",
}
export enum youtubeLink {
  trainingImportance = "https://www.youtube.com/embed/t7l1cqDj1tA?si=ZJCQXJYDLzDwLLvm"
}
